export const FETCH_DATA = 'FETCH_DATA'
export const FETCH_DATA_FETCH_SUCCESS = 'FETCH_DATA_FETCH_SUCCESS'
export const FETCH_DATA_FETCH_ERROR = 'FETCH_DATA_FETCH_ERROR'
export const FETCH_DATA_FETCH_FAILURE = 'FETCH_DATA_FETCH_FAILURE'